config/routes.rb
Rails.application.routes.draw do
  
  # root "users//sessions#new"
  # get "/" => "users/sessions#new"
  get 'admins' => 'admins#top' 
  
  root 'home#top'
  
  resources :matches do
    post 'match_end' => 'matches#match_end'
    get 'select_member' => 'matches#select_member'
    get 'enter_point' => 'matches#enter_point'
    post 'enter_point' => 'matches#input_point'
    resources :entries
    resources :match_innings do 
      resources :match_results, only: [:create, :update]
    end
    resources :users, except: [:index, :show, :create, :update, :destroy] do 
      resources :match_results
    end
  end
  
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
  }

  devise_scope :user do
    # root :to => "users/sessions#new"
    get "signup", :to => "users/registrations#new"
    get "verify", :to => "users/registrations#verify"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
  
  resources :users, only: [:index, :show] do
    collection do
      get "mypage", :to => "users#mypage"
    end
    
    member do
      get :following, :followers
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/match.rb
class Match < ApplicationRecord
    
    
    has_many :entries, dependent: :destroy
    accepts_nested_attributes_for :entries
    
    has_many :match_innings, dependent: :destroy
    
    
    
    def match_point_total
        
          hash = Hash.new
          match_results = MatchResult.where(match_inning_id: self.match_innings.pluck(:id))
          total = match_results.pluck(:point).sum
          
          average = total/self.entries.count.to_f.round(3)
          user_point_total = Hash.new
          self.entries.each do |entry|
              user_total = match_results.where(user_id: entry.user_id).pluck(:point).sum
              user_point_total.store(entry.user_id, (user_total.to_f).round(2) - average)
              # puts average*10 - user_total*10
          end
          
          hash.store("total", total)
          hash.store("all_average", average)
          hash.store("user_point_total", user_point_total)
        return hash
    end
    
    def match_point_calc
          hash = Hash.new
          self.match_point_total["user_point_total"].each {|user_id, differ|
            if unit_price.present?
              hash.store(user_id, differ*self.unit_price.round(2))
            else
              hash.store(user_id, differ.round(2))
            end
          }
        return hash
        
    end
    
    
    def games_of_match
      self.match_innings
    end
    
 
    
    def match_total_by_user(user_id)
            match_innings_ids = self.match_innings.order(:inning_number).pluck(:id)
            total = MatchResult.where(user_id: user_id, match_inning_id: match_innings_ids).pluck(:point).sum
        return total
    end
    
    def ranked_hash_in_match
      hash = Hash.new { |h,k| h[k] = {} }  # { match.id => { user.id => total VP }}
      
      participates = self.entries
      participates.each do |user|
        hash[self.id][user.user_id] =  self.match_total_by_user(user.user_id)  #このmatchでのあるuserの合計VP
      end
      hash[self.id] = hash[self.id].sort_by{ |_, v| -v }.to_h
      return hash
    end
    
    def rank_in_match_sorted
      return rank_in_method(self.ranked_hash_in_match, self.id)
    end
    
    
    
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  
  before_action :authenticate_user!
  before_action :get_match, only: [:show, :edit, :destroy]
  
  def new
    @match = Match.new
  end
  
  def create
    @match = Match.new(match_params)
    if @match.save
      redirect_to new_match_entry_path(@match)
    else
      flash[:error] = "試合登録できませんでした"
      puts "試合登録できませんでした"
      render 'new'
    end
  end

  def index
    @matches = Match.all.order(created_at: :desc).page(params[:page]).per(10)
  end
  
  def enter_point
    @match = Match.find(params[:match_id])
    @extended_versions = ExtendedVersion.where.not(id: 3)
    # 上は収穫祭・錬金術を別にするために収穫祭・錬金術を非表示にするため
    # @extended_versions = ExtendedVersion.all
    @entries = @match.entries
    puts "~~~~~~~ @match = #{@match.id} --- @entries count #{@entries.count}"
    @match_innings = MatchInning.where(match_id: @match.id).order(:inning_number)
    puts "@match_innings = #{@match_innings.count}"
    # @match_innings = @match.match_innings
    unless @match.match_end
      @match_inning = MatchInning.new(match_id: @match.id)
      @match_result = @match_inning.match_results.build
    end
    # @match_result = @MatchResult.new(match_inning_id: @match_inning)
  end
  
  def input_point 
    
  end
  
  def match_end
    @match = Match.find(params[:match_id])
    @match.update(match_end: true)
    redirect_to match_enter_point_path(@match)
  end

  def edit
  end
  
  def update
  end

  def show
  end
  
  def select_member
    @match = Match.find(params[:match_id])
    @users = User.all.order(:skill_level)
  end
  
  def destroy
    match_name = @match.name
    if  @match.destroy
      flash[:notice]= "#{match_name}をマッチを削除しました。"
      redirect_to matches_path
    else
      flash[:error] = "#{match_name}をマッチを削除できませんでした。"
      redirect_to match_enter_point_path(@match)
    end
  end
  
  private
    def get_match
      @match = Match.find(params[:id])
    end
    
    def match_params
      params.require(:match).permit(:name, :place, :start_time, :end_time, :held_date, :unit_price)
    end
    
    def input_point_params 
      params.require(:match_inning).permit(match_results_attributes: [:point])
    end
    
end

app/helpers/matches_helper.rb
module MatchesHelper
    
    
    
end

app/views/matches/enter_point.html.erb
<div id="enter_point">
  <h3 class="title">ゲーム点数入力</h3>
  <h4><%= @match.name %></h4>
  <div><%= @match.created_at.strftime("%Y年%-m月%-d日 %a %H: %M") %></div>
  <div>単価：<%= @match.unit_price %></div>
  <hr>
  <% width_col_1 = "col-xs-1 col-ms-1 col-md-1 col-lg-1" %>
  <% width_col_2 = "col-xs-2 col-ms-2 col-md-2 col-lg-2" %>
  <%= form_with model: @match_inning,  url: "/matches/#{@match.id}/match_innings", local: true do |f| %>
    <section class="table-responsive">
      <table class="table table-bordered table-striped">
            <thead>
              <tr>
                  <th class="<%= width_col_1 %>"></th>
                  <td class="<%= width_col_2 %>"></td>
                 <% @entries.each do |entry| %>
                   <td scope="row" class="<%= width_col_2 %> td_user_name"><%= entry.user.name %></td>
                 <% end %>
              </tr>
            </thead>
            
          <% innings = @match_innings.present? ? @match_innings.last.inning_number : 0 %>
          <!--< innings.times do |i| %>-->
            <tbody class="enter_point_tbody">
                <% @match_innings.each do |mi| %>
                  <!--<= f.hidden_field :inning_number, value: mi.inning_number %>-->
                  <tr>
                      <% if @match.match_end %>
                        <th style="text-align: center; width: 30px;"><%= mi.inning_number %></th>
                      <% else %>
                        <th style="text-align: center; width: 30px;"><%= link_to mi.inning_number, edit_match_match_inning_path(@match, mi), class: "enter-point-inning" %></th>
                      <% end %>
                      <td class="td_used_version" style="text-align: center; width: 30px;">
                       <% mi.used_versions_name.each do |vu| %>
                          <span><%= vu %></span>
                          <br>
                        <% end %>                     
                      </td>
                         <% max_point = MatchResult.where(match_inning_id: mi.id).pluck(:point).max %>
                         <% @entries.each do |entry| %>
                           <% user_point = MatchResult.find_by(match_inning_id: mi.id, user_id: entry.user_id).point %>
                           <% if mr = MatchResult.find_by(match_inning_id: mi.id, user_id: entry.user_id) %>
                             <td class="td_point_histrory <%= user_point === max_point ? "victory_user_of_inning":"" %>"><%= MatchResult.find_by(match_inning_id: mi.id, user_id: entry.user_id).point %></td>
                           <% end %>
                         <% end %>
                  </tr>
                <% end %>
                  <% unless @match.match_end %>
                    <tr>
                      <th style="text-align: center;">
                        <%= innings + 1 %>
                        <!--<= f.collection_select(:version_used, @extended_versions, :id, :name, {:prompt => "Please Select a Sector"}, {:multiple => true}) %>-->
                      </th>
                      <td></td>
                      <% @entries.each_with_index do |entry, i| %>
                        <%= f.fields_for :match_results do |mr| %>
                            <td class="td_new_point"><%= mr.hidden_field :user_id, value: entry.user_id %><%= mr.number_field :point, value: (@match_results.present? ? @match_results[i.to_s][:point].to_i : nil), style: "width: 80%;" %></td>
                        <% end%> 
                      <% end %>
                    </tr>
                  <% end %>
                  <tr style="background: #d3d3d39c;">
                    <th class="th_match_total">合計</th>
                    <td></td>
                    <% @entries.each do |entry| %>
                      <td class="td_match_total" style="color: #fff; background: #00bcd4;"><%= @match.match_total_by_user(entry.user_id) %></td>
                    <% end %>
                  </tr>
                  <tr style="background: #d3d3d39c;">
                    <th class="th_match_total">結果</th>
                    <td></td>
                    <% @entries.each do |entry| %>
                      <td class="td_match_total" style="color: #fff; background: #607d8b;"><%= @match.match_point_calc[entry.user_id].positive? ?
                                                                                               @match.match_point_calc[entry.user_id].floor : 
                                                                                               @match.match_point_calc[entry.user_id].ceil %></td>
                    <% end %>
                  </tr>                  
  
            </tbody>
          <!--<end %>-->
      </table>
    </section>
    <!-- 使用するversionを選択  -->
    <% unless @match.match_end %>
      <div>
        <% @extended_versions.all.each do |c| %>
          <%= f.check_box :extended_version_ids, { multiple: true, include_hidden: false }, c.id %>
          <span class="extended_version_checkbox"><%= c.name %></span>
        <% end %>
      </div>
      <%= f.submit "Point入力", class: "btn btn-primary" %>
    <% end %>
  <% end %>  <!-- form end -->
  <% unless @match.match_end %>
    <div class="end_match_button"><%= link_to "マッチ終了", match_match_end_path(@match), method: :post, class: "btn btn-danger" %></div>
  <% else %>
    <div class="end_match_message">終了済マッチ</div>
  <% end %>
  <% if current_user.admin %>
    <div class="end_match_message"><%= link_to "マッチ削除", "/matches/#{@match.id}", method: :delete, data: { confirm: "【確認】#{@match.name}を削除してもよろしいですか？" }, class: "btn btn-link" %> </div>
  <% end %>
</div>

app/views/matches/index.html.erb
<div class="matches-title">
  <h3>試合一覧（<%= Match.all.count %>）</h3>
  <div><%= link_to "Add Match", "/matches/new", class: "btn btn-success" %></div>
</div>
<hr>
<table class="table table-striped table-bordered matches">
  <thead>
    <tr>
      <th scope="col">Match Name</th>
      <th scope="col">Held</th>
      <th scope="col">NOP</th>
    </tr>
  </thead>
  <tbody>
   <% @matches.each do |match| %>     
       <tr>
         <th scope="row"><%= link_to match.name.truncate(10), match_enter_point_path(match) %></th>
         <td class="matches-match-created_at"><%= match.created_at.strftime("%Y-%m-%d %H:%M") %></td>
         <td class="matches-match-created_at"><%= match.entries.count %></td>
       </tr>
   <% end %>    
  </tbody>
</table>
<%= paginate @matches, theme: 'bootstrap-5' %>

<style>
.matches-title {
    display: flex;
    justify-content: space-between;
}

    
</style>

app/views/matches/new.html.erb
<div id="match-new">
  <h2>ゲーム登録</h2>
  <hr>
  <%= form_with model: @match do |f| %>
    <div>name: <%= f.text_field :name, class: "form-control match-name" %></div>
    <div>単価: <%= f.number_field :unit_price, class: "form-control unit-price"  %></div>
    <div><%= f.submit class: "btn btn-success match-new-submit" %></div>
  <% end %>
</div>

app/views/matches/select_member.html.erb
<h2>メンバー選択</h2>
<hr>
<h3>試合</h3>
試合名:<%= @match.name %>
<hr>
<%= form_with url: "" do |f| %>
    <% @users.all.each do |user| %>
      <div>
          <%= f.check_box :user_ids, { multiple: true, include_hidden: false }, user.id %>
          <%= user.name %>
      </div>
    <% end %>
    
    <%= f.submit "決定", class: "btn btn-primary" %>
<% end %>

app/views/matches/show.html.erb
<h1>Matches#show</h1>
<p>Find me in app/views/matches/show.html.erb</p>